DESCRIPTION = "Linux kernel for RockPi-S"

require recipes-kernel/linux/linux-yocto.inc

DEPENDS += "openssl-native"

SRC_URI = " \
	git://github.com/radxa/kernel.git;branch=stable-4.4-rockpis; \
"

SRCREV = "7f01019a77e8d02f91e3bbb4e7fd071be085fc27"
LINUX_VERSION = "4.4.143"

# Override local version in order to use the one generated by linux build system
# And not "yocto-standard"
LINUX_VERSION_EXTENSION = ""
PR = "r1"
PV = "${LINUX_VERSION}"

# Include only supported boards for now
COMPATIBLE_MACHINE = "(rk3036|rk3066|rk3288|rk3328|rk3399|rk3308)"
deltask kernel_configme

do_compile_append() {
	oe_runmake dtbs
}

do_deploy_append() {
	mkdir -p ${DEPLOYDIR}/overlays
	cp -rf ${WORKDIR}/linux-rockpi_S_rk3308-standard-build/arch/arm64/boot/dts/rockchip/overlays-rockpiS/console-on-ttyS2.dtbo ${DEPLOYDIR}/overlays
	cp -rf ${WORKDIR}/linux-rockpi_S_rk3308-standard-build/arch/arm64/boot/dts/rockchip/overlays-rockpiS/console-on-ttyS4.dtbo ${DEPLOYDIR}/overlays
	cp -rf ${S}/arch/arm64/boot/dts/rockchip/overlays-rockpiS/hw_intfc.conf ${DEPLOYDIR}/overlays
}
